name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build static files
        run: |
          mkdir assets/build
          touch assets/build/test.html

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2

      - name: E2E
        run: |
          CGO_ENABLED=0 go build -o cloudreve .
          docker build . -t cloudreve/cloudreve:latest

          cd e2e && ./start.sh
